#version 450

layout (local_size_x = 1) in;

#include "neighbors.glsl"
#include "fluid_simulation_params.glsl"
#include "indirect.glsl"

void main() 
{
  // TODO
  // Initializer solver, solve x and lambda
  dispatch_indirect_commands[0] = uvec4((params.num_particles + params.num_particles * params.max_num_neighbors + 255) / 256, 1, 1, 0);
  
  // Solve delta lambda
  dispatch_indirect_commands[1] = uvec4(max(1, (params.num_particles + 255) / 256), 1, 1, 0);
}
