#version 450

layout (local_size_x = 256) in;

#include "particle.glsl"
#include "simulation_params.glsl"

void main()
{
  uint index = gl_GlobalInvocationID.x;
  if (index >= params.num_particles)
    return;

  const float mass = particles[index].properties.x;

  particles[index].velocity += params.dt * particles[index].external_force / mass;
  particles[index].prev_position = particles[index].position;
  particles[index].position += params.dt * particles[index].velocity;
}
