#version 450

layout (local_size_x = 256) in;

#include "simulation_params.glsl"
#include "../uniform_grid/uniform_grid.glsl"

void main()
{
  uint hash_index = gl_GlobalInvocationID.x;
  if (hash_index >= num_hash_buckets)
    return;

  if (hash_index == 0)
  {
    // Cell size big enough for collision detection
    grid.cell_size = vec3(params.h);
    grid.num_pairs = 0;
  }

  grid_hash_table.head[hash_index] = -1;
}
