#version 450

layout (local_size_x = 256) in;

#include "fluid/particle.glsl"
#include "fluid/simulation_params.glsl"

void main()
{
  uint index = gl_GlobalInvocationID.x;
  if (index >= params.num_particles)
    return;

  particles[index].velocity += params.dt * particles[index].external_force;
  particles[index].prev_position = particles[index].position;
  particles[index].position += params.dt * particles[index].velocity;
}
