#version 450

layout (local_size_x = 256) in;

#include "particle/particle.glsl"
#include "particle/simulation_params.glsl"
#include "uniform_grid/uniform_grid.glsl"

void main()
{
  uint particle_id = gl_GlobalInvocationID.x;
  if (particle_id >= params.num_particles)
    return;

  vec3 position = particles[particle_id].position.xyz;
  float radius = params.radius;
  
  AddSphereToGrid(particle_id, position, 2.f * radius);
}
